version: "3.7"
services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGUSER=postgres
      - PGDATABASE=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  api:
    env_file:
      - server/.env
    environment:
      DATABASE_URL: "postgres://postgres@db:5432/postgres"
    build: ./server
    depends_on:
      - db
    ports: 
      [3001:3001]
    restart: always
  client:
    build: ./client
    depends_on:
      - api
    ports: 
      [3000:3000]
    restart: always